// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.dmetasoul.lakesoul.meta.entity;

/**
 * Protobuf type {@code proto.entity.DataCommitInfo}
 */
public final class DataCommitInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.entity.DataCommitInfo)
    DataCommitInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataCommitInfo.newBuilder() to construct.
  private DataCommitInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataCommitInfo() {
    tableId_ = "";
    partitionDesc_ = "";
    commitId_ = "";
    fileOps_ = java.util.Collections.emptyList();
    commitOp_ = 0;
    domain_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataCommitInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataCommitInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataCommitInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.class, com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.Builder.class);
  }

  public static final int TABLEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableId_ = "";
  /**
   * <code>string tableId = 1;</code>
   * @return The tableId.
   */
  @java.lang.Override
  public java.lang.String getTableId() {
    java.lang.Object ref = tableId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableId_ = s;
      return s;
    }
  }
  /**
   * <code>string tableId = 1;</code>
   * @return The bytes for tableId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableIdBytes() {
    java.lang.Object ref = tableId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITIONDESC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object partitionDesc_ = "";
  /**
   * <code>string partitionDesc = 2;</code>
   * @return The partitionDesc.
   */
  @java.lang.Override
  public java.lang.String getPartitionDesc() {
    java.lang.Object ref = partitionDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partitionDesc_ = s;
      return s;
    }
  }
  /**
   * <code>string partitionDesc = 2;</code>
   * @return The bytes for partitionDesc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartitionDescBytes() {
    java.lang.Object ref = partitionDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partitionDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMITID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commitId_ = "";
  /**
   * <code>string commitId = 3;</code>
   * @return The commitId.
   */
  @java.lang.Override
  public java.lang.String getCommitId() {
    java.lang.Object ref = commitId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitId_ = s;
      return s;
    }
  }
  /**
   * <code>string commitId = 3;</code>
   * @return The bytes for commitId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommitIdBytes() {
    java.lang.Object ref = commitId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILEOPS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.dmetasoul.lakesoul.meta.entity.DataFileOp> fileOps_;
  /**
   * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.dmetasoul.lakesoul.meta.entity.DataFileOp> getFileOpsList() {
    return fileOps_;
  }
  /**
   * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder> 
      getFileOpsOrBuilderList() {
    return fileOps_;
  }
  /**
   * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
   */
  @java.lang.Override
  public int getFileOpsCount() {
    return fileOps_.size();
  }
  /**
   * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.DataFileOp getFileOps(int index) {
    return fileOps_.get(index);
  }
  /**
   * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder getFileOpsOrBuilder(
      int index) {
    return fileOps_.get(index);
  }

  public static final int COMMITOP_FIELD_NUMBER = 5;
  private int commitOp_ = 0;
  /**
   * <code>.proto.entity.CommitOp commitOp = 5;</code>
   * @return The enum numeric value on the wire for commitOp.
   */
  @java.lang.Override public int getCommitOpValue() {
    return commitOp_;
  }
  /**
   * <code>.proto.entity.CommitOp commitOp = 5;</code>
   * @return The commitOp.
   */
  @java.lang.Override public com.dmetasoul.lakesoul.meta.entity.CommitOp getCommitOp() {
    com.dmetasoul.lakesoul.meta.entity.CommitOp result = com.dmetasoul.lakesoul.meta.entity.CommitOp.forNumber(commitOp_);
    return result == null ? com.dmetasoul.lakesoul.meta.entity.CommitOp.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int COMMITTED_FIELD_NUMBER = 8;
  private boolean committed_ = false;
  /**
   * <code>bool committed = 8;</code>
   * @return The committed.
   */
  @java.lang.Override
  public boolean getCommitted() {
    return committed_;
  }

  public static final int DOMAIN_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <code>string domain = 9;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <code>string domain = 9;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitionDesc_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, partitionDesc_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commitId_);
    }
    for (int i = 0; i < fileOps_.size(); i++) {
      output.writeMessage(4, fileOps_.get(i));
    }
    if (commitOp_ != com.dmetasoul.lakesoul.meta.entity.CommitOp.CompactionCommit.getNumber()) {
      output.writeEnum(5, commitOp_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (committed_ != false) {
      output.writeBool(8, committed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, domain_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitionDesc_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, partitionDesc_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commitId_);
    }
    for (int i = 0; i < fileOps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, fileOps_.get(i));
    }
    if (commitOp_ != com.dmetasoul.lakesoul.meta.entity.CommitOp.CompactionCommit.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, commitOp_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (committed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, committed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, domain_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dmetasoul.lakesoul.meta.entity.DataCommitInfo)) {
      return super.equals(obj);
    }
    com.dmetasoul.lakesoul.meta.entity.DataCommitInfo other = (com.dmetasoul.lakesoul.meta.entity.DataCommitInfo) obj;

    if (!getTableId()
        .equals(other.getTableId())) return false;
    if (!getPartitionDesc()
        .equals(other.getPartitionDesc())) return false;
    if (!getCommitId()
        .equals(other.getCommitId())) return false;
    if (!getFileOpsList()
        .equals(other.getFileOpsList())) return false;
    if (commitOp_ != other.commitOp_) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getCommitted()
        != other.getCommitted()) return false;
    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLEID_FIELD_NUMBER;
    hash = (53 * hash) + getTableId().hashCode();
    hash = (37 * hash) + PARTITIONDESC_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionDesc().hashCode();
    hash = (37 * hash) + COMMITID_FIELD_NUMBER;
    hash = (53 * hash) + getCommitId().hashCode();
    if (getFileOpsCount() > 0) {
      hash = (37 * hash) + FILEOPS_FIELD_NUMBER;
      hash = (53 * hash) + getFileOpsList().hashCode();
    }
    hash = (37 * hash) + COMMITOP_FIELD_NUMBER;
    hash = (53 * hash) + commitOp_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + COMMITTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCommitted());
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dmetasoul.lakesoul.meta.entity.DataCommitInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.entity.DataCommitInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.entity.DataCommitInfo)
      com.dmetasoul.lakesoul.meta.entity.DataCommitInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataCommitInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataCommitInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.class, com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.Builder.class);
    }

    // Construct using com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tableId_ = "";
      partitionDesc_ = "";
      commitId_ = "";
      if (fileOpsBuilder_ == null) {
        fileOps_ = java.util.Collections.emptyList();
      } else {
        fileOps_ = null;
        fileOpsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      commitOp_ = 0;
      timestamp_ = 0L;
      committed_ = false;
      domain_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataCommitInfo_descriptor;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataCommitInfo getDefaultInstanceForType() {
      return com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataCommitInfo build() {
      com.dmetasoul.lakesoul.meta.entity.DataCommitInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataCommitInfo buildPartial() {
      com.dmetasoul.lakesoul.meta.entity.DataCommitInfo result = new com.dmetasoul.lakesoul.meta.entity.DataCommitInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dmetasoul.lakesoul.meta.entity.DataCommitInfo result) {
      if (fileOpsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          fileOps_ = java.util.Collections.unmodifiableList(fileOps_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fileOps_ = fileOps_;
      } else {
        result.fileOps_ = fileOpsBuilder_.build();
      }
    }

    private void buildPartial0(com.dmetasoul.lakesoul.meta.entity.DataCommitInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tableId_ = tableId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.partitionDesc_ = partitionDesc_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.commitId_ = commitId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.commitOp_ = commitOp_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.committed_ = committed_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.domain_ = domain_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dmetasoul.lakesoul.meta.entity.DataCommitInfo) {
        return mergeFrom((com.dmetasoul.lakesoul.meta.entity.DataCommitInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dmetasoul.lakesoul.meta.entity.DataCommitInfo other) {
      if (other == com.dmetasoul.lakesoul.meta.entity.DataCommitInfo.getDefaultInstance()) return this;
      if (!other.getTableId().isEmpty()) {
        tableId_ = other.tableId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPartitionDesc().isEmpty()) {
        partitionDesc_ = other.partitionDesc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCommitId().isEmpty()) {
        commitId_ = other.commitId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (fileOpsBuilder_ == null) {
        if (!other.fileOps_.isEmpty()) {
          if (fileOps_.isEmpty()) {
            fileOps_ = other.fileOps_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFileOpsIsMutable();
            fileOps_.addAll(other.fileOps_);
          }
          onChanged();
        }
      } else {
        if (!other.fileOps_.isEmpty()) {
          if (fileOpsBuilder_.isEmpty()) {
            fileOpsBuilder_.dispose();
            fileOpsBuilder_ = null;
            fileOps_ = other.fileOps_;
            bitField0_ = (bitField0_ & ~0x00000008);
            fileOpsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFileOpsFieldBuilder() : null;
          } else {
            fileOpsBuilder_.addAllMessages(other.fileOps_);
          }
        }
      }
      if (other.commitOp_ != 0) {
        setCommitOpValue(other.getCommitOpValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getCommitted() != false) {
        setCommitted(other.getCommitted());
      }
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tableId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              partitionDesc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              commitId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.dmetasoul.lakesoul.meta.entity.DataFileOp m =
                  input.readMessage(
                      com.dmetasoul.lakesoul.meta.entity.DataFileOp.parser(),
                      extensionRegistry);
              if (fileOpsBuilder_ == null) {
                ensureFileOpsIsMutable();
                fileOps_.add(m);
              } else {
                fileOpsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              commitOp_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 64: {
              committed_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 64
            case 74: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableId_ = "";
    /**
     * <code>string tableId = 1;</code>
     * @return The tableId.
     */
    public java.lang.String getTableId() {
      java.lang.Object ref = tableId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableId = 1;</code>
     * @return The bytes for tableId.
     */
    public com.google.protobuf.ByteString
        getTableIdBytes() {
      java.lang.Object ref = tableId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableId = 1;</code>
     * @param value The tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableId() {
      tableId_ = getDefaultInstance().getTableId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 1;</code>
     * @param value The bytes for tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object partitionDesc_ = "";
    /**
     * <code>string partitionDesc = 2;</code>
     * @return The partitionDesc.
     */
    public java.lang.String getPartitionDesc() {
      java.lang.Object ref = partitionDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partitionDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partitionDesc = 2;</code>
     * @return The bytes for partitionDesc.
     */
    public com.google.protobuf.ByteString
        getPartitionDescBytes() {
      java.lang.Object ref = partitionDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partitionDesc = 2;</code>
     * @param value The partitionDesc to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      partitionDesc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string partitionDesc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitionDesc() {
      partitionDesc_ = getDefaultInstance().getPartitionDesc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string partitionDesc = 2;</code>
     * @param value The bytes for partitionDesc to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      partitionDesc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object commitId_ = "";
    /**
     * <code>string commitId = 3;</code>
     * @return The commitId.
     */
    public java.lang.String getCommitId() {
      java.lang.Object ref = commitId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commitId = 3;</code>
     * @return The bytes for commitId.
     */
    public com.google.protobuf.ByteString
        getCommitIdBytes() {
      java.lang.Object ref = commitId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commitId = 3;</code>
     * @param value The commitId to set.
     * @return This builder for chaining.
     */
    public Builder setCommitId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commitId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string commitId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitId() {
      commitId_ = getDefaultInstance().getCommitId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string commitId = 3;</code>
     * @param value The bytes for commitId to set.
     * @return This builder for chaining.
     */
    public Builder setCommitIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commitId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.dmetasoul.lakesoul.meta.entity.DataFileOp> fileOps_ =
      java.util.Collections.emptyList();
    private void ensureFileOpsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        fileOps_ = new java.util.ArrayList<com.dmetasoul.lakesoul.meta.entity.DataFileOp>(fileOps_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.DataFileOp, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder, com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder> fileOpsBuilder_;

    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.DataFileOp> getFileOpsList() {
      if (fileOpsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fileOps_);
      } else {
        return fileOpsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public int getFileOpsCount() {
      if (fileOpsBuilder_ == null) {
        return fileOps_.size();
      } else {
        return fileOpsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp getFileOps(int index) {
      if (fileOpsBuilder_ == null) {
        return fileOps_.get(index);
      } else {
        return fileOpsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder setFileOps(
        int index, com.dmetasoul.lakesoul.meta.entity.DataFileOp value) {
      if (fileOpsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileOpsIsMutable();
        fileOps_.set(index, value);
        onChanged();
      } else {
        fileOpsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder setFileOps(
        int index, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder builderForValue) {
      if (fileOpsBuilder_ == null) {
        ensureFileOpsIsMutable();
        fileOps_.set(index, builderForValue.build());
        onChanged();
      } else {
        fileOpsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder addFileOps(com.dmetasoul.lakesoul.meta.entity.DataFileOp value) {
      if (fileOpsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileOpsIsMutable();
        fileOps_.add(value);
        onChanged();
      } else {
        fileOpsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder addFileOps(
        int index, com.dmetasoul.lakesoul.meta.entity.DataFileOp value) {
      if (fileOpsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileOpsIsMutable();
        fileOps_.add(index, value);
        onChanged();
      } else {
        fileOpsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder addFileOps(
        com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder builderForValue) {
      if (fileOpsBuilder_ == null) {
        ensureFileOpsIsMutable();
        fileOps_.add(builderForValue.build());
        onChanged();
      } else {
        fileOpsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder addFileOps(
        int index, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder builderForValue) {
      if (fileOpsBuilder_ == null) {
        ensureFileOpsIsMutable();
        fileOps_.add(index, builderForValue.build());
        onChanged();
      } else {
        fileOpsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder addAllFileOps(
        java.lang.Iterable<? extends com.dmetasoul.lakesoul.meta.entity.DataFileOp> values) {
      if (fileOpsBuilder_ == null) {
        ensureFileOpsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileOps_);
        onChanged();
      } else {
        fileOpsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder clearFileOps() {
      if (fileOpsBuilder_ == null) {
        fileOps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        fileOpsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public Builder removeFileOps(int index) {
      if (fileOpsBuilder_ == null) {
        ensureFileOpsIsMutable();
        fileOps_.remove(index);
        onChanged();
      } else {
        fileOpsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder getFileOpsBuilder(
        int index) {
      return getFileOpsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder getFileOpsOrBuilder(
        int index) {
      if (fileOpsBuilder_ == null) {
        return fileOps_.get(index);  } else {
        return fileOpsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder> 
         getFileOpsOrBuilderList() {
      if (fileOpsBuilder_ != null) {
        return fileOpsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fileOps_);
      }
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder addFileOpsBuilder() {
      return getFileOpsFieldBuilder().addBuilder(
          com.dmetasoul.lakesoul.meta.entity.DataFileOp.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder addFileOpsBuilder(
        int index) {
      return getFileOpsFieldBuilder().addBuilder(
          index, com.dmetasoul.lakesoul.meta.entity.DataFileOp.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.DataFileOp fileOps = 4;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder> 
         getFileOpsBuilderList() {
      return getFileOpsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.DataFileOp, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder, com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder> 
        getFileOpsFieldBuilder() {
      if (fileOpsBuilder_ == null) {
        fileOpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dmetasoul.lakesoul.meta.entity.DataFileOp, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder, com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder>(
                fileOps_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        fileOps_ = null;
      }
      return fileOpsBuilder_;
    }

    private int commitOp_ = 0;
    /**
     * <code>.proto.entity.CommitOp commitOp = 5;</code>
     * @return The enum numeric value on the wire for commitOp.
     */
    @java.lang.Override public int getCommitOpValue() {
      return commitOp_;
    }
    /**
     * <code>.proto.entity.CommitOp commitOp = 5;</code>
     * @param value The enum numeric value on the wire for commitOp to set.
     * @return This builder for chaining.
     */
    public Builder setCommitOpValue(int value) {
      commitOp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.CommitOp commitOp = 5;</code>
     * @return The commitOp.
     */
    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.CommitOp getCommitOp() {
      com.dmetasoul.lakesoul.meta.entity.CommitOp result = com.dmetasoul.lakesoul.meta.entity.CommitOp.forNumber(commitOp_);
      return result == null ? com.dmetasoul.lakesoul.meta.entity.CommitOp.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.entity.CommitOp commitOp = 5;</code>
     * @param value The commitOp to set.
     * @return This builder for chaining.
     */
    public Builder setCommitOp(com.dmetasoul.lakesoul.meta.entity.CommitOp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      commitOp_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.CommitOp commitOp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitOp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      commitOp_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private boolean committed_ ;
    /**
     * <code>bool committed = 8;</code>
     * @return The committed.
     */
    @java.lang.Override
    public boolean getCommitted() {
      return committed_;
    }
    /**
     * <code>bool committed = 8;</code>
     * @param value The committed to set.
     * @return This builder for chaining.
     */
    public Builder setCommitted(boolean value) {

      committed_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool committed = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitted() {
      bitField0_ = (bitField0_ & ~0x00000040);
      committed_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object domain_ = "";
    /**
     * <code>string domain = 9;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain = 9;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain = 9;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 9;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.entity.DataCommitInfo)
  }

  // @@protoc_insertion_point(class_scope:proto.entity.DataCommitInfo)
  private static final com.dmetasoul.lakesoul.meta.entity.DataCommitInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dmetasoul.lakesoul.meta.entity.DataCommitInfo();
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataCommitInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataCommitInfo>
      PARSER = new com.google.protobuf.AbstractParser<DataCommitInfo>() {
    @java.lang.Override
    public DataCommitInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataCommitInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataCommitInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.DataCommitInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

