// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.dmetasoul.lakesoul.meta.entity;

/**
 * Protobuf type {@code proto.entity.DataFileOp}
 */
public final class DataFileOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.entity.DataFileOp)
    DataFileOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataFileOp.newBuilder() to construct.
  private DataFileOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataFileOp() {
    path_ = "";
    fileOp_ = "";
    fileExistCols_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataFileOp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataFileOp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataFileOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dmetasoul.lakesoul.meta.entity.DataFileOp.class, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object path_ = "";
  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILEOP_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileOp_ = "";
  /**
   * <code>string fileOp = 2;</code>
   * @return The fileOp.
   */
  @java.lang.Override
  public java.lang.String getFileOp() {
    java.lang.Object ref = fileOp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileOp_ = s;
      return s;
    }
  }
  /**
   * <code>string fileOp = 2;</code>
   * @return The bytes for fileOp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileOpBytes() {
    java.lang.Object ref = fileOp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileOp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private long size_ = 0L;
  /**
   * <code>int64 size = 3;</code>
   * @return The size.
   */
  @java.lang.Override
  public long getSize() {
    return size_;
  }

  public static final int FILEEXISTCOLS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileExistCols_ = "";
  /**
   * <code>string fileExistCols = 4;</code>
   * @return The fileExistCols.
   */
  @java.lang.Override
  public java.lang.String getFileExistCols() {
    java.lang.Object ref = fileExistCols_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileExistCols_ = s;
      return s;
    }
  }
  /**
   * <code>string fileExistCols = 4;</code>
   * @return The bytes for fileExistCols.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileExistColsBytes() {
    java.lang.Object ref = fileExistCols_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileExistCols_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileOp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileOp_);
    }
    if (size_ != 0L) {
      output.writeInt64(3, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileExistCols_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileExistCols_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileOp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileOp_);
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileExistCols_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileExistCols_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dmetasoul.lakesoul.meta.entity.DataFileOp)) {
      return super.equals(obj);
    }
    com.dmetasoul.lakesoul.meta.entity.DataFileOp other = (com.dmetasoul.lakesoul.meta.entity.DataFileOp) obj;

    if (!getPath()
        .equals(other.getPath())) return false;
    if (!getFileOp()
        .equals(other.getFileOp())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getFileExistCols()
        .equals(other.getFileExistCols())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + FILEOP_FIELD_NUMBER;
    hash = (53 * hash) + getFileOp().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSize());
    hash = (37 * hash) + FILEEXISTCOLS_FIELD_NUMBER;
    hash = (53 * hash) + getFileExistCols().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dmetasoul.lakesoul.meta.entity.DataFileOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.entity.DataFileOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.entity.DataFileOp)
      com.dmetasoul.lakesoul.meta.entity.DataFileOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataFileOp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataFileOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dmetasoul.lakesoul.meta.entity.DataFileOp.class, com.dmetasoul.lakesoul.meta.entity.DataFileOp.Builder.class);
    }

    // Construct using com.dmetasoul.lakesoul.meta.entity.DataFileOp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      path_ = "";
      fileOp_ = "";
      size_ = 0L;
      fileExistCols_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_DataFileOp_descriptor;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp getDefaultInstanceForType() {
      return com.dmetasoul.lakesoul.meta.entity.DataFileOp.getDefaultInstance();
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp build() {
      com.dmetasoul.lakesoul.meta.entity.DataFileOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.DataFileOp buildPartial() {
      com.dmetasoul.lakesoul.meta.entity.DataFileOp result = new com.dmetasoul.lakesoul.meta.entity.DataFileOp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dmetasoul.lakesoul.meta.entity.DataFileOp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.path_ = path_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileOp_ = fileOp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fileExistCols_ = fileExistCols_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dmetasoul.lakesoul.meta.entity.DataFileOp) {
        return mergeFrom((com.dmetasoul.lakesoul.meta.entity.DataFileOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dmetasoul.lakesoul.meta.entity.DataFileOp other) {
      if (other == com.dmetasoul.lakesoul.meta.entity.DataFileOp.getDefaultInstance()) return this;
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFileOp().isEmpty()) {
        fileOp_ = other.fileOp_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getSize() != 0L) {
        setSize(other.getSize());
      }
      if (!other.getFileExistCols().isEmpty()) {
        fileExistCols_ = other.fileExistCols_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              path_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fileOp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              size_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              fileExistCols_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object path_ = "";
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      path_ = getDefaultInstance().getPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object fileOp_ = "";
    /**
     * <code>string fileOp = 2;</code>
     * @return The fileOp.
     */
    public java.lang.String getFileOp() {
      java.lang.Object ref = fileOp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileOp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileOp = 2;</code>
     * @return The bytes for fileOp.
     */
    public com.google.protobuf.ByteString
        getFileOpBytes() {
      java.lang.Object ref = fileOp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileOp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileOp = 2;</code>
     * @param value The fileOp to set.
     * @return This builder for chaining.
     */
    public Builder setFileOp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileOp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string fileOp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileOp() {
      fileOp_ = getDefaultInstance().getFileOp();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string fileOp = 2;</code>
     * @param value The bytes for fileOp to set.
     * @return This builder for chaining.
     */
    public Builder setFileOpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileOp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <code>int64 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }
    /**
     * <code>int64 size = 3;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {

      size_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fileExistCols_ = "";
    /**
     * <code>string fileExistCols = 4;</code>
     * @return The fileExistCols.
     */
    public java.lang.String getFileExistCols() {
      java.lang.Object ref = fileExistCols_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileExistCols_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileExistCols = 4;</code>
     * @return The bytes for fileExistCols.
     */
    public com.google.protobuf.ByteString
        getFileExistColsBytes() {
      java.lang.Object ref = fileExistCols_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileExistCols_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileExistCols = 4;</code>
     * @param value The fileExistCols to set.
     * @return This builder for chaining.
     */
    public Builder setFileExistCols(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileExistCols_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string fileExistCols = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileExistCols() {
      fileExistCols_ = getDefaultInstance().getFileExistCols();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string fileExistCols = 4;</code>
     * @param value The bytes for fileExistCols to set.
     * @return This builder for chaining.
     */
    public Builder setFileExistColsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileExistCols_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.entity.DataFileOp)
  }

  // @@protoc_insertion_point(class_scope:proto.entity.DataFileOp)
  private static final com.dmetasoul.lakesoul.meta.entity.DataFileOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dmetasoul.lakesoul.meta.entity.DataFileOp();
  }

  public static com.dmetasoul.lakesoul.meta.entity.DataFileOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataFileOp>
      PARSER = new com.google.protobuf.AbstractParser<DataFileOp>() {
    @java.lang.Override
    public DataFileOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataFileOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataFileOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.DataFileOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

