// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.dmetasoul.lakesoul.meta.entity;

/**
 * Protobuf type {@code proto.entity.MetaInfo}
 */
public final class MetaInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.entity.MetaInfo)
    MetaInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaInfo.newBuilder() to construct.
  private MetaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaInfo() {
    listPartition_ = java.util.Collections.emptyList();
    readPartitionInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetaInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_MetaInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_MetaInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dmetasoul.lakesoul.meta.entity.MetaInfo.class, com.dmetasoul.lakesoul.meta.entity.MetaInfo.Builder.class);
  }

  public static final int LISTPARTITION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> listPartition_;
  /**
   * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> getListPartitionList() {
    return listPartition_;
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
      getListPartitionOrBuilderList() {
    return listPartition_;
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
   */
  @java.lang.Override
  public int getListPartitionCount() {
    return listPartition_.size();
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.PartitionInfo getListPartition(int index) {
    return listPartition_.get(index);
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder getListPartitionOrBuilder(
      int index) {
    return listPartition_.get(index);
  }

  public static final int TABLEINFO_FIELD_NUMBER = 2;
  private com.dmetasoul.lakesoul.meta.entity.TableInfo tableInfo_;
  /**
   * <code>.proto.entity.TableInfo tableInfo = 2;</code>
   * @return Whether the tableInfo field is set.
   */
  @java.lang.Override
  public boolean hasTableInfo() {
    return tableInfo_ != null;
  }
  /**
   * <code>.proto.entity.TableInfo tableInfo = 2;</code>
   * @return The tableInfo.
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.TableInfo getTableInfo() {
    return tableInfo_ == null ? com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance() : tableInfo_;
  }
  /**
   * <code>.proto.entity.TableInfo tableInfo = 2;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder getTableInfoOrBuilder() {
    return tableInfo_ == null ? com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance() : tableInfo_;
  }

  public static final int READPARTITIONINFO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> readPartitionInfo_;
  /**
   * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> getReadPartitionInfoList() {
    return readPartitionInfo_;
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
      getReadPartitionInfoOrBuilderList() {
    return readPartitionInfo_;
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
   */
  @java.lang.Override
  public int getReadPartitionInfoCount() {
    return readPartitionInfo_.size();
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.PartitionInfo getReadPartitionInfo(int index) {
    return readPartitionInfo_.get(index);
  }
  /**
   * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
   */
  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder getReadPartitionInfoOrBuilder(
      int index) {
    return readPartitionInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < listPartition_.size(); i++) {
      output.writeMessage(1, listPartition_.get(i));
    }
    if (tableInfo_ != null) {
      output.writeMessage(2, getTableInfo());
    }
    for (int i = 0; i < readPartitionInfo_.size(); i++) {
      output.writeMessage(3, readPartitionInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < listPartition_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, listPartition_.get(i));
    }
    if (tableInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTableInfo());
    }
    for (int i = 0; i < readPartitionInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, readPartitionInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dmetasoul.lakesoul.meta.entity.MetaInfo)) {
      return super.equals(obj);
    }
    com.dmetasoul.lakesoul.meta.entity.MetaInfo other = (com.dmetasoul.lakesoul.meta.entity.MetaInfo) obj;

    if (!getListPartitionList()
        .equals(other.getListPartitionList())) return false;
    if (hasTableInfo() != other.hasTableInfo()) return false;
    if (hasTableInfo()) {
      if (!getTableInfo()
          .equals(other.getTableInfo())) return false;
    }
    if (!getReadPartitionInfoList()
        .equals(other.getReadPartitionInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getListPartitionCount() > 0) {
      hash = (37 * hash) + LISTPARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getListPartitionList().hashCode();
    }
    if (hasTableInfo()) {
      hash = (37 * hash) + TABLEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getTableInfo().hashCode();
    }
    if (getReadPartitionInfoCount() > 0) {
      hash = (37 * hash) + READPARTITIONINFO_FIELD_NUMBER;
      hash = (53 * hash) + getReadPartitionInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dmetasoul.lakesoul.meta.entity.MetaInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.entity.MetaInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.entity.MetaInfo)
      com.dmetasoul.lakesoul.meta.entity.MetaInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_MetaInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_MetaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dmetasoul.lakesoul.meta.entity.MetaInfo.class, com.dmetasoul.lakesoul.meta.entity.MetaInfo.Builder.class);
    }

    // Construct using com.dmetasoul.lakesoul.meta.entity.MetaInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (listPartitionBuilder_ == null) {
        listPartition_ = java.util.Collections.emptyList();
      } else {
        listPartition_ = null;
        listPartitionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      tableInfo_ = null;
      if (tableInfoBuilder_ != null) {
        tableInfoBuilder_.dispose();
        tableInfoBuilder_ = null;
      }
      if (readPartitionInfoBuilder_ == null) {
        readPartitionInfo_ = java.util.Collections.emptyList();
      } else {
        readPartitionInfo_ = null;
        readPartitionInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_MetaInfo_descriptor;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.MetaInfo getDefaultInstanceForType() {
      return com.dmetasoul.lakesoul.meta.entity.MetaInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.MetaInfo build() {
      com.dmetasoul.lakesoul.meta.entity.MetaInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.MetaInfo buildPartial() {
      com.dmetasoul.lakesoul.meta.entity.MetaInfo result = new com.dmetasoul.lakesoul.meta.entity.MetaInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dmetasoul.lakesoul.meta.entity.MetaInfo result) {
      if (listPartitionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          listPartition_ = java.util.Collections.unmodifiableList(listPartition_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listPartition_ = listPartition_;
      } else {
        result.listPartition_ = listPartitionBuilder_.build();
      }
      if (readPartitionInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          readPartitionInfo_ = java.util.Collections.unmodifiableList(readPartitionInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.readPartitionInfo_ = readPartitionInfo_;
      } else {
        result.readPartitionInfo_ = readPartitionInfoBuilder_.build();
      }
    }

    private void buildPartial0(com.dmetasoul.lakesoul.meta.entity.MetaInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tableInfo_ = tableInfoBuilder_ == null
            ? tableInfo_
            : tableInfoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dmetasoul.lakesoul.meta.entity.MetaInfo) {
        return mergeFrom((com.dmetasoul.lakesoul.meta.entity.MetaInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dmetasoul.lakesoul.meta.entity.MetaInfo other) {
      if (other == com.dmetasoul.lakesoul.meta.entity.MetaInfo.getDefaultInstance()) return this;
      if (listPartitionBuilder_ == null) {
        if (!other.listPartition_.isEmpty()) {
          if (listPartition_.isEmpty()) {
            listPartition_ = other.listPartition_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListPartitionIsMutable();
            listPartition_.addAll(other.listPartition_);
          }
          onChanged();
        }
      } else {
        if (!other.listPartition_.isEmpty()) {
          if (listPartitionBuilder_.isEmpty()) {
            listPartitionBuilder_.dispose();
            listPartitionBuilder_ = null;
            listPartition_ = other.listPartition_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listPartitionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListPartitionFieldBuilder() : null;
          } else {
            listPartitionBuilder_.addAllMessages(other.listPartition_);
          }
        }
      }
      if (other.hasTableInfo()) {
        mergeTableInfo(other.getTableInfo());
      }
      if (readPartitionInfoBuilder_ == null) {
        if (!other.readPartitionInfo_.isEmpty()) {
          if (readPartitionInfo_.isEmpty()) {
            readPartitionInfo_ = other.readPartitionInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReadPartitionInfoIsMutable();
            readPartitionInfo_.addAll(other.readPartitionInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.readPartitionInfo_.isEmpty()) {
          if (readPartitionInfoBuilder_.isEmpty()) {
            readPartitionInfoBuilder_.dispose();
            readPartitionInfoBuilder_ = null;
            readPartitionInfo_ = other.readPartitionInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            readPartitionInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReadPartitionInfoFieldBuilder() : null;
          } else {
            readPartitionInfoBuilder_.addAllMessages(other.readPartitionInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.dmetasoul.lakesoul.meta.entity.PartitionInfo m =
                  input.readMessage(
                      com.dmetasoul.lakesoul.meta.entity.PartitionInfo.parser(),
                      extensionRegistry);
              if (listPartitionBuilder_ == null) {
                ensureListPartitionIsMutable();
                listPartition_.add(m);
              } else {
                listPartitionBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTableInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.dmetasoul.lakesoul.meta.entity.PartitionInfo m =
                  input.readMessage(
                      com.dmetasoul.lakesoul.meta.entity.PartitionInfo.parser(),
                      extensionRegistry);
              if (readPartitionInfoBuilder_ == null) {
                ensureReadPartitionInfoIsMutable();
                readPartitionInfo_.add(m);
              } else {
                readPartitionInfoBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> listPartition_ =
      java.util.Collections.emptyList();
    private void ensureListPartitionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        listPartition_ = new java.util.ArrayList<com.dmetasoul.lakesoul.meta.entity.PartitionInfo>(listPartition_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> listPartitionBuilder_;

    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> getListPartitionList() {
      if (listPartitionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listPartition_);
      } else {
        return listPartitionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public int getListPartitionCount() {
      if (listPartitionBuilder_ == null) {
        return listPartition_.size();
      } else {
        return listPartitionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo getListPartition(int index) {
      if (listPartitionBuilder_ == null) {
        return listPartition_.get(index);
      } else {
        return listPartitionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder setListPartition(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (listPartitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPartitionIsMutable();
        listPartition_.set(index, value);
        onChanged();
      } else {
        listPartitionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder setListPartition(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (listPartitionBuilder_ == null) {
        ensureListPartitionIsMutable();
        listPartition_.set(index, builderForValue.build());
        onChanged();
      } else {
        listPartitionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder addListPartition(com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (listPartitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPartitionIsMutable();
        listPartition_.add(value);
        onChanged();
      } else {
        listPartitionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder addListPartition(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (listPartitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPartitionIsMutable();
        listPartition_.add(index, value);
        onChanged();
      } else {
        listPartitionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder addListPartition(
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (listPartitionBuilder_ == null) {
        ensureListPartitionIsMutable();
        listPartition_.add(builderForValue.build());
        onChanged();
      } else {
        listPartitionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder addListPartition(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (listPartitionBuilder_ == null) {
        ensureListPartitionIsMutable();
        listPartition_.add(index, builderForValue.build());
        onChanged();
      } else {
        listPartitionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder addAllListPartition(
        java.lang.Iterable<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfo> values) {
      if (listPartitionBuilder_ == null) {
        ensureListPartitionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listPartition_);
        onChanged();
      } else {
        listPartitionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder clearListPartition() {
      if (listPartitionBuilder_ == null) {
        listPartition_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listPartitionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public Builder removeListPartition(int index) {
      if (listPartitionBuilder_ == null) {
        ensureListPartitionIsMutable();
        listPartition_.remove(index);
        onChanged();
      } else {
        listPartitionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder getListPartitionBuilder(
        int index) {
      return getListPartitionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder getListPartitionOrBuilder(
        int index) {
      if (listPartitionBuilder_ == null) {
        return listPartition_.get(index);  } else {
        return listPartitionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
         getListPartitionOrBuilderList() {
      if (listPartitionBuilder_ != null) {
        return listPartitionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listPartition_);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder addListPartitionBuilder() {
      return getListPartitionFieldBuilder().addBuilder(
          com.dmetasoul.lakesoul.meta.entity.PartitionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder addListPartitionBuilder(
        int index) {
      return getListPartitionFieldBuilder().addBuilder(
          index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo listPartition = 1;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder> 
         getListPartitionBuilderList() {
      return getListPartitionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
        getListPartitionFieldBuilder() {
      if (listPartitionBuilder_ == null) {
        listPartitionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder>(
                listPartition_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        listPartition_ = null;
      }
      return listPartitionBuilder_;
    }

    private com.dmetasoul.lakesoul.meta.entity.TableInfo tableInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.TableInfo, com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder, com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder> tableInfoBuilder_;
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     * @return Whether the tableInfo field is set.
     */
    public boolean hasTableInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     * @return The tableInfo.
     */
    public com.dmetasoul.lakesoul.meta.entity.TableInfo getTableInfo() {
      if (tableInfoBuilder_ == null) {
        return tableInfo_ == null ? com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance() : tableInfo_;
      } else {
        return tableInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public Builder setTableInfo(com.dmetasoul.lakesoul.meta.entity.TableInfo value) {
      if (tableInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tableInfo_ = value;
      } else {
        tableInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public Builder setTableInfo(
        com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder builderForValue) {
      if (tableInfoBuilder_ == null) {
        tableInfo_ = builderForValue.build();
      } else {
        tableInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public Builder mergeTableInfo(com.dmetasoul.lakesoul.meta.entity.TableInfo value) {
      if (tableInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          tableInfo_ != null &&
          tableInfo_ != com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance()) {
          getTableInfoBuilder().mergeFrom(value);
        } else {
          tableInfo_ = value;
        }
      } else {
        tableInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public Builder clearTableInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tableInfo_ = null;
      if (tableInfoBuilder_ != null) {
        tableInfoBuilder_.dispose();
        tableInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder getTableInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTableInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder getTableInfoOrBuilder() {
      if (tableInfoBuilder_ != null) {
        return tableInfoBuilder_.getMessageOrBuilder();
      } else {
        return tableInfo_ == null ?
            com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance() : tableInfo_;
      }
    }
    /**
     * <code>.proto.entity.TableInfo tableInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.TableInfo, com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder, com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder> 
        getTableInfoFieldBuilder() {
      if (tableInfoBuilder_ == null) {
        tableInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dmetasoul.lakesoul.meta.entity.TableInfo, com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder, com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder>(
                getTableInfo(),
                getParentForChildren(),
                isClean());
        tableInfo_ = null;
      }
      return tableInfoBuilder_;
    }

    private java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> readPartitionInfo_ =
      java.util.Collections.emptyList();
    private void ensureReadPartitionInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        readPartitionInfo_ = new java.util.ArrayList<com.dmetasoul.lakesoul.meta.entity.PartitionInfo>(readPartitionInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> readPartitionInfoBuilder_;

    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo> getReadPartitionInfoList() {
      if (readPartitionInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(readPartitionInfo_);
      } else {
        return readPartitionInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public int getReadPartitionInfoCount() {
      if (readPartitionInfoBuilder_ == null) {
        return readPartitionInfo_.size();
      } else {
        return readPartitionInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo getReadPartitionInfo(int index) {
      if (readPartitionInfoBuilder_ == null) {
        return readPartitionInfo_.get(index);
      } else {
        return readPartitionInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder setReadPartitionInfo(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (readPartitionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.set(index, value);
        onChanged();
      } else {
        readPartitionInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder setReadPartitionInfo(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (readPartitionInfoBuilder_ == null) {
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        readPartitionInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder addReadPartitionInfo(com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (readPartitionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.add(value);
        onChanged();
      } else {
        readPartitionInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder addReadPartitionInfo(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo value) {
      if (readPartitionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.add(index, value);
        onChanged();
      } else {
        readPartitionInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder addReadPartitionInfo(
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (readPartitionInfoBuilder_ == null) {
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.add(builderForValue.build());
        onChanged();
      } else {
        readPartitionInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder addReadPartitionInfo(
        int index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder builderForValue) {
      if (readPartitionInfoBuilder_ == null) {
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        readPartitionInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder addAllReadPartitionInfo(
        java.lang.Iterable<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfo> values) {
      if (readPartitionInfoBuilder_ == null) {
        ensureReadPartitionInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, readPartitionInfo_);
        onChanged();
      } else {
        readPartitionInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder clearReadPartitionInfo() {
      if (readPartitionInfoBuilder_ == null) {
        readPartitionInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        readPartitionInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public Builder removeReadPartitionInfo(int index) {
      if (readPartitionInfoBuilder_ == null) {
        ensureReadPartitionInfoIsMutable();
        readPartitionInfo_.remove(index);
        onChanged();
      } else {
        readPartitionInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder getReadPartitionInfoBuilder(
        int index) {
      return getReadPartitionInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder getReadPartitionInfoOrBuilder(
        int index) {
      if (readPartitionInfoBuilder_ == null) {
        return readPartitionInfo_.get(index);  } else {
        return readPartitionInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public java.util.List<? extends com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
         getReadPartitionInfoOrBuilderList() {
      if (readPartitionInfoBuilder_ != null) {
        return readPartitionInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(readPartitionInfo_);
      }
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder addReadPartitionInfoBuilder() {
      return getReadPartitionInfoFieldBuilder().addBuilder(
          com.dmetasoul.lakesoul.meta.entity.PartitionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder addReadPartitionInfoBuilder(
        int index) {
      return getReadPartitionInfoFieldBuilder().addBuilder(
          index, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.entity.PartitionInfo readPartitionInfo = 3;</code>
     */
    public java.util.List<com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder> 
         getReadPartitionInfoBuilderList() {
      return getReadPartitionInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder> 
        getReadPartitionInfoFieldBuilder() {
      if (readPartitionInfoBuilder_ == null) {
        readPartitionInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dmetasoul.lakesoul.meta.entity.PartitionInfo, com.dmetasoul.lakesoul.meta.entity.PartitionInfo.Builder, com.dmetasoul.lakesoul.meta.entity.PartitionInfoOrBuilder>(
                readPartitionInfo_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        readPartitionInfo_ = null;
      }
      return readPartitionInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.entity.MetaInfo)
  }

  // @@protoc_insertion_point(class_scope:proto.entity.MetaInfo)
  private static final com.dmetasoul.lakesoul.meta.entity.MetaInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dmetasoul.lakesoul.meta.entity.MetaInfo();
  }

  public static com.dmetasoul.lakesoul.meta.entity.MetaInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaInfo>
      PARSER = new com.google.protobuf.AbstractParser<MetaInfo>() {
    @java.lang.Override
    public MetaInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetaInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.MetaInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

