// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.dmetasoul.lakesoul.meta.entity;

/**
 * Protobuf type {@code proto.entity.TableInfo}
 */
public final class TableInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.entity.TableInfo)
    TableInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableInfo.newBuilder() to construct.
  private TableInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableInfo() {
    tableId_ = "";
    tableNamespace_ = "";
    tableName_ = "";
    tablePath_ = "";
    tableSchema_ = "";
    properties_ = "";
    partitions_ = "";
    domain_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TableInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_TableInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_TableInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dmetasoul.lakesoul.meta.entity.TableInfo.class, com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder.class);
  }

  public static final int TABLEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableId_ = "";
  /**
   * <code>string tableId = 1;</code>
   * @return The tableId.
   */
  @java.lang.Override
  public java.lang.String getTableId() {
    java.lang.Object ref = tableId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableId_ = s;
      return s;
    }
  }
  /**
   * <code>string tableId = 1;</code>
   * @return The bytes for tableId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableIdBytes() {
    java.lang.Object ref = tableId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAMESPACE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableNamespace_ = "";
  /**
   * <code>string tableNamespace = 2;</code>
   * @return The tableNamespace.
   */
  @java.lang.Override
  public java.lang.String getTableNamespace() {
    java.lang.Object ref = tableNamespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableNamespace_ = s;
      return s;
    }
  }
  /**
   * <code>string tableNamespace = 2;</code>
   * @return The bytes for tableNamespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNamespaceBytes() {
    java.lang.Object ref = tableNamespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableNamespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableName_ = "";
  /**
   * <code>string tableName = 3;</code>
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string tableName = 3;</code>
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLEPATH_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tablePath_ = "";
  /**
   * <code>string tablePath = 4;</code>
   * @return The tablePath.
   */
  @java.lang.Override
  public java.lang.String getTablePath() {
    java.lang.Object ref = tablePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tablePath_ = s;
      return s;
    }
  }
  /**
   * <code>string tablePath = 4;</code>
   * @return The bytes for tablePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTablePathBytes() {
    java.lang.Object ref = tablePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tablePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLESCHEMA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableSchema_ = "";
  /**
   * <code>string tableSchema = 5;</code>
   * @return The tableSchema.
   */
  @java.lang.Override
  public java.lang.String getTableSchema() {
    java.lang.Object ref = tableSchema_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableSchema_ = s;
      return s;
    }
  }
  /**
   * <code>string tableSchema = 5;</code>
   * @return The bytes for tableSchema.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableSchemaBytes() {
    java.lang.Object ref = tableSchema_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableSchema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROPERTIES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object properties_ = "";
  /**
   * <code>string properties = 7;</code>
   * @return The properties.
   */
  @java.lang.Override
  public java.lang.String getProperties() {
    java.lang.Object ref = properties_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      properties_ = s;
      return s;
    }
  }
  /**
   * <code>string properties = 7;</code>
   * @return The bytes for properties.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPropertiesBytes() {
    java.lang.Object ref = properties_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      properties_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITIONS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object partitions_ = "";
  /**
   * <code>string partitions = 8;</code>
   * @return The partitions.
   */
  @java.lang.Override
  public java.lang.String getPartitions() {
    java.lang.Object ref = partitions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partitions_ = s;
      return s;
    }
  }
  /**
   * <code>string partitions = 8;</code>
   * @return The bytes for partitions.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartitionsBytes() {
    java.lang.Object ref = partitions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partitions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAIN_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <code>string domain = 9;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <code>string domain = 9;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableNamespace_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableNamespace_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tablePath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tablePath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableSchema_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tableSchema_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(properties_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, properties_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitions_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, partitions_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, domain_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableNamespace_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableNamespace_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tablePath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tablePath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableSchema_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tableSchema_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(properties_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, properties_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitions_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, partitions_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, domain_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dmetasoul.lakesoul.meta.entity.TableInfo)) {
      return super.equals(obj);
    }
    com.dmetasoul.lakesoul.meta.entity.TableInfo other = (com.dmetasoul.lakesoul.meta.entity.TableInfo) obj;

    if (!getTableId()
        .equals(other.getTableId())) return false;
    if (!getTableNamespace()
        .equals(other.getTableNamespace())) return false;
    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (!getTablePath()
        .equals(other.getTablePath())) return false;
    if (!getTableSchema()
        .equals(other.getTableSchema())) return false;
    if (!getProperties()
        .equals(other.getProperties())) return false;
    if (!getPartitions()
        .equals(other.getPartitions())) return false;
    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLEID_FIELD_NUMBER;
    hash = (53 * hash) + getTableId().hashCode();
    hash = (37 * hash) + TABLENAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getTableNamespace().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + TABLEPATH_FIELD_NUMBER;
    hash = (53 * hash) + getTablePath().hashCode();
    hash = (37 * hash) + TABLESCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getTableSchema().hashCode();
    hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
    hash = (53 * hash) + getProperties().hashCode();
    hash = (37 * hash) + PARTITIONS_FIELD_NUMBER;
    hash = (53 * hash) + getPartitions().hashCode();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmetasoul.lakesoul.meta.entity.TableInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dmetasoul.lakesoul.meta.entity.TableInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.entity.TableInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.entity.TableInfo)
      com.dmetasoul.lakesoul.meta.entity.TableInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_TableInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_TableInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dmetasoul.lakesoul.meta.entity.TableInfo.class, com.dmetasoul.lakesoul.meta.entity.TableInfo.Builder.class);
    }

    // Construct using com.dmetasoul.lakesoul.meta.entity.TableInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tableId_ = "";
      tableNamespace_ = "";
      tableName_ = "";
      tablePath_ = "";
      tableSchema_ = "";
      properties_ = "";
      partitions_ = "";
      domain_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dmetasoul.lakesoul.meta.entity.Entity.internal_static_proto_entity_TableInfo_descriptor;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.TableInfo getDefaultInstanceForType() {
      return com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.TableInfo build() {
      com.dmetasoul.lakesoul.meta.entity.TableInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dmetasoul.lakesoul.meta.entity.TableInfo buildPartial() {
      com.dmetasoul.lakesoul.meta.entity.TableInfo result = new com.dmetasoul.lakesoul.meta.entity.TableInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dmetasoul.lakesoul.meta.entity.TableInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tableId_ = tableId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tableNamespace_ = tableNamespace_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tableName_ = tableName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tablePath_ = tablePath_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tableSchema_ = tableSchema_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.properties_ = properties_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.partitions_ = partitions_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.domain_ = domain_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dmetasoul.lakesoul.meta.entity.TableInfo) {
        return mergeFrom((com.dmetasoul.lakesoul.meta.entity.TableInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dmetasoul.lakesoul.meta.entity.TableInfo other) {
      if (other == com.dmetasoul.lakesoul.meta.entity.TableInfo.getDefaultInstance()) return this;
      if (!other.getTableId().isEmpty()) {
        tableId_ = other.tableId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTableNamespace().isEmpty()) {
        tableNamespace_ = other.tableNamespace_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTablePath().isEmpty()) {
        tablePath_ = other.tablePath_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTableSchema().isEmpty()) {
        tableSchema_ = other.tableSchema_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getProperties().isEmpty()) {
        properties_ = other.properties_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getPartitions().isEmpty()) {
        partitions_ = other.partitions_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tableId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tableNamespace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tableName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              tablePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              tableSchema_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 58: {
              properties_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 58
            case 66: {
              partitions_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 66
            case 74: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableId_ = "";
    /**
     * <code>string tableId = 1;</code>
     * @return The tableId.
     */
    public java.lang.String getTableId() {
      java.lang.Object ref = tableId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableId = 1;</code>
     * @return The bytes for tableId.
     */
    public com.google.protobuf.ByteString
        getTableIdBytes() {
      java.lang.Object ref = tableId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableId = 1;</code>
     * @param value The tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableId() {
      tableId_ = getDefaultInstance().getTableId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 1;</code>
     * @param value The bytes for tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tableNamespace_ = "";
    /**
     * <code>string tableNamespace = 2;</code>
     * @return The tableNamespace.
     */
    public java.lang.String getTableNamespace() {
      java.lang.Object ref = tableNamespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableNamespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableNamespace = 2;</code>
     * @return The bytes for tableNamespace.
     */
    public com.google.protobuf.ByteString
        getTableNamespaceBytes() {
      java.lang.Object ref = tableNamespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableNamespace = 2;</code>
     * @param value The tableNamespace to set.
     * @return This builder for chaining.
     */
    public Builder setTableNamespace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableNamespace_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tableNamespace = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableNamespace() {
      tableNamespace_ = getDefaultInstance().getTableNamespace();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tableNamespace = 2;</code>
     * @param value The bytes for tableNamespace to set.
     * @return This builder for chaining.
     */
    public Builder setTableNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableNamespace_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <code>string tableName = 3;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableName = 3;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableName = 3;</code>
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      tableName_ = getDefaultInstance().getTableName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 3;</code>
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object tablePath_ = "";
    /**
     * <code>string tablePath = 4;</code>
     * @return The tablePath.
     */
    public java.lang.String getTablePath() {
      java.lang.Object ref = tablePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tablePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tablePath = 4;</code>
     * @return The bytes for tablePath.
     */
    public com.google.protobuf.ByteString
        getTablePathBytes() {
      java.lang.Object ref = tablePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tablePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tablePath = 4;</code>
     * @param value The tablePath to set.
     * @return This builder for chaining.
     */
    public Builder setTablePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tablePath_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string tablePath = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTablePath() {
      tablePath_ = getDefaultInstance().getTablePath();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string tablePath = 4;</code>
     * @param value The bytes for tablePath to set.
     * @return This builder for chaining.
     */
    public Builder setTablePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tablePath_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object tableSchema_ = "";
    /**
     * <code>string tableSchema = 5;</code>
     * @return The tableSchema.
     */
    public java.lang.String getTableSchema() {
      java.lang.Object ref = tableSchema_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableSchema_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableSchema = 5;</code>
     * @return The bytes for tableSchema.
     */
    public com.google.protobuf.ByteString
        getTableSchemaBytes() {
      java.lang.Object ref = tableSchema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableSchema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableSchema = 5;</code>
     * @param value The tableSchema to set.
     * @return This builder for chaining.
     */
    public Builder setTableSchema(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableSchema_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string tableSchema = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableSchema() {
      tableSchema_ = getDefaultInstance().getTableSchema();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string tableSchema = 5;</code>
     * @param value The bytes for tableSchema to set.
     * @return This builder for chaining.
     */
    public Builder setTableSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableSchema_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object properties_ = "";
    /**
     * <code>string properties = 7;</code>
     * @return The properties.
     */
    public java.lang.String getProperties() {
      java.lang.Object ref = properties_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        properties_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string properties = 7;</code>
     * @return The bytes for properties.
     */
    public com.google.protobuf.ByteString
        getPropertiesBytes() {
      java.lang.Object ref = properties_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        properties_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string properties = 7;</code>
     * @param value The properties to set.
     * @return This builder for chaining.
     */
    public Builder setProperties(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      properties_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string properties = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProperties() {
      properties_ = getDefaultInstance().getProperties();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string properties = 7;</code>
     * @param value The bytes for properties to set.
     * @return This builder for chaining.
     */
    public Builder setPropertiesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      properties_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object partitions_ = "";
    /**
     * <code>string partitions = 8;</code>
     * @return The partitions.
     */
    public java.lang.String getPartitions() {
      java.lang.Object ref = partitions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partitions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partitions = 8;</code>
     * @return The bytes for partitions.
     */
    public com.google.protobuf.ByteString
        getPartitionsBytes() {
      java.lang.Object ref = partitions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partitions = 8;</code>
     * @param value The partitions to set.
     * @return This builder for chaining.
     */
    public Builder setPartitions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      partitions_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string partitions = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitions() {
      partitions_ = getDefaultInstance().getPartitions();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string partitions = 8;</code>
     * @param value The bytes for partitions to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      partitions_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object domain_ = "";
    /**
     * <code>string domain = 9;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain = 9;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain = 9;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 9;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.entity.TableInfo)
  }

  // @@protoc_insertion_point(class_scope:proto.entity.TableInfo)
  private static final com.dmetasoul.lakesoul.meta.entity.TableInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dmetasoul.lakesoul.meta.entity.TableInfo();
  }

  public static com.dmetasoul.lakesoul.meta.entity.TableInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableInfo>
      PARSER = new com.google.protobuf.AbstractParser<TableInfo>() {
    @java.lang.Override
    public TableInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TableInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dmetasoul.lakesoul.meta.entity.TableInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

