# SPDX-FileCopyrightText: 2026 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "lakesoul-observability"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true
publish = false

[dependencies]
lakesoul-build-info = { path = "../lakesoul-build-info" }
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
opentelemetry = { version = "0.32.0", default-features = false, features = [
  "trace",
] }
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = [
  "grpc-tonic",
  "tls-roots",
  "trace",
] }
opentelemetry_sdk = { version = "0.32.1", default-features = false, features = [
  "rt-tokio",
  "trace",
] }
tokio.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.33.0"
tracing-subscriber = { workspace = true }

[lints]
workspace = true
