#!/usr/bin/env just --justfile

SPARK_HOME := '~/Downloads/spark-3.3.2-bin-hadoop3'
SPARK_BIN := SPARK_HOME + "/bin"
TARGET := "/Users/mag1cian/.m2/repository/com/dmetasoul/spark-e2e/3.0.0-SNAPSHOT/spark-e2e-3.0.0-SNAPSHOT.jar"

#TARGET := "~/dev/internship/LakeSoul/lakesoul-integ-test/flink/target/integ.flink-3.0.0-SNAPSHOT.jar"

MAIN_CLASS := "com.dmetasoul.e2e.SparkData"

#LAKE_SOUL_LIB := "~/dev/internship/LakeSoul/lakesoul-flink/target/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar"

LAKE_SOUL_LIB := "~/.m2/repository/com/dmetasoul/lakesoul-spark/3.3-3.0.0-SNAPSHOT/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar"

add-lakesoul:
    cp {{ LAKE_SOUL_LIB }} {{ SPARK_HOME }}/jars

build:
    mvn clean package -DskipTests

install:
    mvn clean install -DskipTests

clean-data:
    rm -rf /tmp/lakesoul/data/sink

remove_mvn:
    @rm -rf ~/.m2/repository/com/dmetasoul

run which: clean-data install
    {{ SPARK_BIN }}/spark-submit --class {{ MAIN_CLASS }}{{ which }} --master local[4] {{ TARGET }}
