#!/usr/bin/env just --justfile

SPARK_HOME := '~/opt/spark-3.3.2-bin-hadoop3'
SPARK_BIN := SPARK_HOME + "/bin"
TARGET := "/.m2/repository/com/dmetasoul/spark-e2e/3.0.0-SNAPSHOT/spark-e2e-3.0.0-SNAPSHOT.jar"

#TARGET := "~/dev/internship/LakeSoul/lakesoul-integ-test/flink/target/integ.flink-3.0.0-SNAPSHOT.jar"

MAIN_CLASS := "com.dmetasoul.e2e.SparkData"

#LAKE_SOUL_LIB := "~/dev/internship/LakeSoul/lakesoul-flink/target/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar"

LAKE_SOUL_LIB := "~/.m2/repository/com/dmetasoul/lakesoul-spark/3.3-3.0.0-SNAPSHOT/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar"
S3_LAKESOUL_LIB := "s3://dmetasoul-bucket/lakesoul/lakesoul-e2e/target/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar"

add-lakesoul:
    cp {{ LAKE_SOUL_LIB }} {{ SPARK_HOME }}/jars

build:
    mvn clean package -DskipTests

install:
    mvn clean install -DskipTests

clean-data:
    rm -rf /tmp/lakesoul/e2e/spark/

upload oss:
    mcli cp {{LAKE_SOUL_LIB}} {{oss}}/dmetasoul-bucket/lakesoul/lakesoul-e2e/target/lakesoul-spark-3.3-3.0.0-SNAPSHOT.jar

remove_mvn:
    @rm -rf ~/.m2/repository/com/dmetasoul

run which: 
    {{ SPARK_BIN }}/spark-submit --jars {{S3_LAKESOUL_LIB}} --class {{ MAIN_CLASS }}{{ which }} --master local[4] {{ TARGET }} \
      --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.467 \
      --conf spark.hadoop.fs.s3a.access.key=jiax \
      --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
      --conf spark.hadoop.fs.s3a.fast.upload=true \
      --conf spark.hadoop.fs.s3a.secret.key=jiaxjiax 
