# SPDX-FileCopyrightText: LakeSoul Contributors
# 
# SPDX-License-Identifier: Apache-2.0
spark: 
  deploy: "local"

flink:
  deploy: "local"

init:
  type: "flink" 
  name: "DataInit"
  entry: "com.dmetasoul.e2e.FlinkDataInit"
  mode: "session"

# sink means write to lakesoul
sinks:
  - type: "spark"
    name: "DataSink"
    entry: "com.dmetasoul.e2e.SparkDataSink"
    mode: "session"

# source means read from lakesoul
sources:
  - type: "spark"
    name: "DataSource"
    entry: "com.dmetasoul.e2e.SparkDataSource"
    mode: "session"