# SPDX-FileCopyrightText: LakeSoul Contributors
# 
# SPDX-License-Identifier: Apache-2.0
version: "3.0.0-SNAPSHOT"

spark: 
  deploy: "local"

flink:
  deploy: "local"

init:
  type: "flink" 
  name: "DataInit"
  entry: "com.dmetasoul.e2e.FlinkDataInit"
  mode: "session"


# sink means write to lakesoul
sinks:
  - type: "flink"
    name: "DataSink"
    entry: "com.dmetasoul.e2e.FlinkDataSink"
    mode: "session"

# source means read from lakesoul
sources:
  - type: "flink"
    name: "DataSource"
    entry: "com.dmetasoul.e2e.FlinkDataSource"
    mode: "session"