test:
    ACCESS_KEY=minioadmin1 SECRET_KEY=minioadmin1 END_POINT=http://localhost:9000 BUCKET=lakesoul-test-bucket LAKESOUL_VERSION=3.0.0-SNAPSHOT ./.venv/bin/python3.13 -m unittest ./test.py

run:
    uv run main.py

debug:
    python3 ./main.py --dir /Users/mag1cian/dev/internship run
old_test:
    python3 ./main.py --fresh --repo https://github.com/mag1c1an1/LakeSoul.git --branch tmp_name run  

help:
    python3 ./main.py --help⏎      