FLINK_HOME := '~/Downloads/flink-1.20.1'
FLINK_BIN := FLINK_HOME + "/bin"
TARGET := "~/dev/internship/LakeSoul/lakesoul-integ-test/flink/target/integ.flink-3.0.0-SNAPSHOT.jar"
MAIN_CLASS := "com.dmetasoul.FlinkJob"

#LAKE_SOUL_LIB := "~/dev/internship/LakeSoul/lakesoul-flink/target/lakesoul-flink-1.20-3.0.0-SNAPSHOT.jar"
LAKE_SOUL_LIB := "~/.m2/repository/com/dmetasoul/lakesoul-flink/1.20-3.0.0-SNAPSHOT/lakesoul-flink-1.20-3.0.0-SNAPSHOT.jar"

add-lakesoul:
    cp {{LAKE_SOUL_LIB}} {{FLINK_HOME}}/lib


cluster cmd:
    {{ FLINK_BIN }}/{{ cmd }}-cluster.sh

build:
    mvn package -DskipTests

clean-data:
    rm -rf /tmp/LAKESOUL/

run: clean-data build
    {{ FLINK_BIN }}/flink run -c {{ MAIN_CLASS }} {{ TARGET }}
