copy-to-java:
  cargo build
  cp target/debug/liblakesoul_io_c.dylib ../lakesoul-common/target/classes/
  cp target/debug/liblakesoul_metadata_c.dylib ../lakesoul-common/target/classes/

log_level := "info"

flight-sql level=log_level:
    RUST_LOG=lakesoul_flight={{level}},lakesoul_metadata={{level}} JWT_AUTH_ENABLED=false RBAC_AUTH_ENABLED=true cargo run --bin flight_sql_server
    
flight-sql-s3 level=log_level:
    RUST_LOG={{level}} cargo run --bin \
      flight_sql_server -- \
      --warehouse-prefix "s3://lakesoul-bucket/flight-test" \
      --endpoint  "http://localhost:9000" \
      --s3-bucket  "lakesoul-test-bucket" \
      --s3-access-key "minioadmin1" \
      --s3-secret-key "minioadmin1"


console level=log_level:
    RUST_LOG={{level}} cargo run --bin console -- \
      --warehouse-prefix "s3://lakesoul-bucket/flight-test" \
      --endpoint  "http://localhost:9000" \
      --s3-bucket  "lakesoul-test-bucket" \
      --s3-access-key "minioadmin1" \
      --s3-secret-key "minioadmin1"
