CREATE EXTERNAL TABLE
nation
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
lineitem
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
part
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
customer
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
orders
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
region
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
supplier
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';

CREATE EXTERNAL TABLE
partsupp
(c1 VARCHAR NOT NULL, c2 INT NOT NULL, c3 DOUBLE , PRIMARY KEY(c1))
STORED AS LAKESOUL
PARTITIONED BY (c2)
LOCATION 'file:///tmp/LAKESOUL/test_lfs_data';
