# pg-service
apiVersion: v1
kind: Service
metadata:
  name: pgsvc
  namespace: default # 修改为你的命名空间
  labels:
    app: pgsvc
spec:
  type: ClusterIP # 内部访问（默认）
  ports:
    - name: postgres
      port: 5432 # 服务端口（外部访问）
      targetPort: 5432 # 容器端口
      protocol: TCP
  selector:
    app: postgres # 匹配Deployment的标签
---
# pg-backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.1ms.run/library/postgres # 选择合适的版本/cloudnative-pg/postgresql
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: metadata-init
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: e2e-config
                  key: LAKESOUL_PG_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: e2e-config
                  key: LAKESOUL_PG_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: e2e-config
                  key: LAKESOUL_PG_DB
      volumes:
        - name: metadata-init
          configMap:
            name: e2e-config
            defaultMode: 0744
            items:
              - key: metadata_init.sql
                path: metadata_init.sql