env := "LAKESOUL_PG_URL=jdbc:postgresql://localhost:5532/py?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_test LAKESOUL_PG_PASSWORD=lakesoul_test"

clean-data:
    rm -rf /tmp/lakesoul/tpch_data

gen-data:
    cd ../rust && {{env}} cargo run -p lakesoul-console -- tpch-gen -p "file:///tmp/lakesoul/tpch_data" --scale-factor 0.1 -n 8 

pytest:
    cd .. && {{env}} python -m pytest python/tests/arrow/test_lakesoul_read.py