# env := "LAKESOUL_PG_URL=jdbc:postgresql://localhost:5532/py?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_test LAKESOUL_PG_PASSWORD=lakesoul_test LAKESOUL_SOURCE_DIR=/home/jiax/LakeSoul LD_LIBRARY_PATH=$JAVA_HOME/lib/server"
# env := "HADOOP_HOME=$HOME/opt/hadoop-3.3.2 LAKESOUL_PG_URL=jdbc:postgresql://localhost:5432/lakesoul_test?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_test LAKESOUL_PG_PASSWORD=lakesoul_test LAKESOUL_SOURCE_DIR=$HOME/Projects/LakeSoul LD_LIBRARY_PATH=$HADOOP_HOME/lib/native"
env := "LAKESOUL_PG_URL=jdbc:postgresql://localhost:5432/lakesoul_test?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_test LAKESOUL_PG_PASSWORD=lakesoul_test LAKESOUL_SOURCE_DIR=$HOME/Projects/LakeSoul"

clean-data:
    rm -rf /tmp/lakesoul/tpch_data

gen-data:
    cargo run -p lakesoul-console -- tpch-gen -p "file:///tmp/lakesoul/tpch_data" --scale-factor 0.1 -n 8
    cargo run --release -p lakesoul-console -- -f test.sql

pytest:
     {{env}} .venv/bin/python -m pytest -s tests

sync:
    uv sync --reinstall-package lakesoul

dist:
    uvx --from 'maturin[zig]' maturin build --release --zig --target x86_64-unknown-linux-gnu --auditwheel repair --compatibility manylinux2014 --out ../dist
