# SPDX-FileCopyrightText: 2026 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0
"""Time-travel timestamp handling.

LakeSoul stores partition commit times as UTC epoch milliseconds generated by
the PostgreSQL server. User-facing time travel accepts ``date``/``datetime``/
ISO-8601 strings and requires an explicit time zone whenever the value carries
none, so a naive value can never silently be interpreted in the wrong zone.
"""

from __future__ import annotations

import datetime as dt
from zoneinfo import ZoneInfo

__all__ = ["resolve_timestamp_ms"]


def _coerce_zone(time_zone: str | dt.tzinfo | None) -> dt.tzinfo | None:
    if time_zone is None:
        return None
    if isinstance(time_zone, dt.tzinfo):
        return time_zone
    if isinstance(time_zone, str):
        try:
            return ZoneInfo(time_zone)
        except Exception as error:
            raise ValueError(f"invalid time_zone {time_zone!r}: {error}") from error
    raise TypeError(
        f"time_zone must be an IANA name or tzinfo, got {type(time_zone).__name__}"
    )


def resolve_timestamp_ms(
    value: dt.date | dt.datetime | str | int,
    time_zone: str | dt.tzinfo | None = None,
) -> int:
    """Resolve a user timestamp to UTC epoch milliseconds.

    ``datetime``/ISO-8601 values with a time zone use it and ignore
    ``time_zone``; values without one require ``time_zone`` and raise
    ``ValueError`` otherwise. A ``date`` covers ``00:00:00`` in ``time_zone``.
    Plain integers are treated as epoch milliseconds.
    """
    if isinstance(value, bool):
        raise TypeError("timestamp must be a date, datetime, ISO-8601 string or int")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        if text.endswith(("Z", "z")):
            text = f"{text[:-1]}+00:00"
        try:
            value = dt.datetime.fromisoformat(text)
        except ValueError:
            try:
                value = dt.date.fromisoformat(text)
            except ValueError as error:
                raise ValueError(f"invalid ISO-8601 timestamp {value!r}") from error
    if isinstance(value, dt.datetime):
        if value.tzinfo is None:
            zone = _coerce_zone(time_zone)
            if zone is None:
                raise ValueError(
                    "timestamp has no time zone; pass time_zone (IANA name) "
                    "or use an aware datetime/ISO-8601 string"
                )
            value = value.replace(tzinfo=zone)
        return int(value.timestamp() * 1000)
    if isinstance(value, dt.date):
        zone = _coerce_zone(time_zone)
        if zone is None:
            raise ValueError(
                "date has no time zone; pass time_zone (IANA name) to pick midnight"
            )
        combined = dt.datetime.combine(value, dt.time.min, tzinfo=zone)
        return int(combined.timestamp() * 1000)
    raise TypeError(
        f"timestamp must be a date, datetime, ISO-8601 string or int, "
        f"got {type(value).__name__}"
    )
