TARGET := "/Users/mag1cian/.m2/repository/com/dmetasoul/flink-e2e/3.0.0-SNAPSHOT/flink-e2e-3.0.0-SNAPSHOT.jar"
HADOOP_CLASSPATH := ""

#TARGET := "~/dev/internship/LakeSoul/lakesoul-integ-test/flink/target/integ.flink-3.0.0-SNAPSHOT.jar"

MAIN_CLASS := "com.dmetasoul.e2e.FlinkData"
LAKE_SOUL_LIB := "file:///Users/mag1cian/.m2/repository/com/dmetasoul/lakesoul-flink/1.20-3.0.0-SNAPSHOT/lakesoul-flink-1.20-3.0.0-SNAPSHOT.jar"

#LAKE_SOUL_LIB := "file:///Users/mag1cian/.m2/repository/com/dmetasoul/lakesoul-flink/1.20-3.0.0-SNAPSHOT"
# HTTPS_LAKE_SOUL_LIB := "http://localhost:9000/lakesoul-test-bucket/m2/lakesoul-flink-1.20-3.0.0-SNAPSHOT.jar"

S3_LAKE_SOUL_LIB := "s3://dmetasoul-bucket/jiax/target/lakesoul-flink-1.20-3.0.0-SNAPSHOT.jar"

#E2E_JOB := "s3://dmetasoul-bucket/jiax/target/flink-e2e-3.0.0-SNAPSHOT.jar"

E2E_JOB := "/Users/mag1cian/.m2/repository/com/dmetasoul/flink-e2e/3.0.0-SNAPSHOT/flink-e2e-3.0.0-SNAPSHOT.jar"
#env := "LAKESOUL_PG_URL=jdbc:postgresql://pgsvc.default.svc.cluster.local:5432/lakesoul_e2e?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_e2e LAKESOUL_PG_PASSWORD=lakesoul_e2e LAKESOUL_PG_DB=lakesoul_e2e"
env := "LAKESOUL_PG_URL=jdbc:postgresql://localhost:5432/lakesoul_e2e?stringtype=unspecified LAKESOUL_PG_USERNAME=lakesoul_e2e LAKESOUL_PG_PASSWORD=lakesoul_e2e LAKESOUL_PG_DB=lakesoul_e2e"
aws_env := "AWS_ACCESS_KEY_ID=minioadmin1 AWS_SECRET_ACCESS_KEY=minioadmin1"

cluster cmd:
    {{ cmd }}-cluster.sh

build:
    mvn package -DskipTests

install:
    mvn install -DskipTests

clean-data:
    rm -rf /tmp/lakesoul/e2e/flink/*

remove_mvn:
    @rm -rf ~/.m2/repository/com/dmetasoul

run which:
    flink run --classpath {{ S3_LAKE_SOUL_LIB }} -c {{ MAIN_CLASS }}{{ which }} {{ E2E_JOB }}

k8s which:
    flink run --classpath {{ LAKE_SOUL_LIB }} -m localhost:8081 -c {{ MAIN_CLASS }}{{ which }} {{ TARGET }}

local which:
    ROOT_LOG_LEVEL=DEBUG flink run --classpath {{ LAKE_SOUL_LIB }} -c {{ MAIN_CLASS }}{{ which }} {{ E2E_JOB }}
