# SPDX-FileCopyrightText: LakeSoul Contributors
# 
# SPDX-License-Identifier: Apache-2.0
spark: 
  deploy: "k8s"
  image: "swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/spark-hadoop-3.3.2:1.0"

flink:
  deploy: "k8s"
  template: "k8s/flink-pod-template.yaml"
  image: "swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-hadoop-3.3.6:1.0"
  timeout: 120

init:
  type: "flink" 
  name: "DataInit"
  entry: "com.dmetasoul.e2e.FlinkDataInit"
  mode: "application"

# sink means write to lakesoul
sinks:
  - type: "spark"
    name: "DataSink"
    entry: "com.dmetasoul.e2e.SparkDataSink"
    mode: "application"
  - type: "flink" 
    name: "DataSink"
    entry: "com.dmetasoul.e2e.FlinkDataSink"
    mode: "application"

# source means read from lakesoul
sources:
  - type: "spark"
    name: "DataSource"
    entry: "com.dmetasoul.e2e.SparkDataSource"
    mode: "application"
  - type: "flink" 
    name: "DataSource"
    entry: "com.dmetasoul.e2e.FlinkDataSource"
    mode: "application"