#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0
#
# LakeSoul test-table fixture generator.
#
# Generates a `test_tables` schema with one table per LakeSoul table flavour
# (append-only / hash primary key / composite PK / range partition / PK+partition
# / CDC / vector index / vortex / all-types), plus the full TPC-H table set with
# primary keys, and populates them with configurable volumes.
#
# Usage:
#   cd rust
#   ./script/test_tables.sh                      # defaults: 1M synthetic rows, TPC-H SF 0.1
#   ROWS=10000000 SF=1 ./script/test_tables.sh   # 10M synthetic rows, TPC-H SF 1
#   WITH_TPCH=0 ./script/test_tables.sh          # synthetic tables only (fast)
#
# Environment:
#   ROWS            rows for the synthetic tables            (default 1000000)
#   VEC_ROWS        rows for the vector-index table          (default 100000)
#   PARTITIONS      range-partition cardinality              (default 32)
#   SF              TPC-H scale factor                       (default 0.1)
#   TPCH_PARTS      TPC-H generation partitions (num_parts)   (default 8)
#   WITH_TPCH       1/0, include the TPC-H tables            (default 1)
#   BUCKETS         hashBucketNum for primary-key tables     (default 16)
#   WORKER_THREADS  console tokio worker threads             (default 16)
#   WAREHOUSE       optional location/warehouse prefix (e.g. s3://bucket/test);
#                   the console's --warehouse-prefix overrides table LOCATIONs
#   CONSOLE_BIN     path to a prebuilt lakesoul-console binary (default: cargo run)
#
# Any extra arguments (e.g. --endpoint/--s3-*) are forwarded to the console.
#
set -euo pipefail

cd "$(dirname "$0")/.."

ROWS="${ROWS:-1000000}"
VEC_ROWS="${VEC_ROWS:-100000}"
PARTITIONS="${PARTITIONS:-32}"
SF="${SF:-0.1}"
TPCH_PARTS="${TPCH_PARTS:-8}"
# The TPC-H UDTFs require the scale factor to be a float literal (`1.0`, not `1`).
case "$SF" in
    *.*) SF_FMT="$SF" ;;
    *) SF_FMT="$SF.0" ;;
esac
WITH_TPCH="${WITH_TPCH:-1}"
BUCKETS="${BUCKETS:-16}"
WORKER_THREADS="${WORKER_THREADS:-16}"
WAREHOUSE="${WAREHOUSE:-}"
LOC="${WAREHOUSE:-file:///tmp/lakesoul/test_tables}"

SQL_FILE="$(mktemp "${TMPDIR:-/tmp}/lakesoul-test-tables-XXXXXX.sql")"
trap 'rm -f "$SQL_FILE"' EXIT

cat > "$SQL_FILE" <<SQL
--
-- Generated by script/test_tables.sh
--   ROWS=$ROWS VEC_ROWS=$VEC_ROWS PARTITIONS=$PARTITIONS SF=$SF
--   WITH_TPCH=$WITH_TPCH TPCH_PARTS=$TPCH_PARTS BUCKETS=$BUCKETS LOC=$LOC
--

CREATE SCHEMA IF NOT EXISTS test_tables;

--
-- 1. Append-only: no primary key, no partition. Duplicate keys are all kept.
--
DROP TABLE IF EXISTS test_tables.append_only;
CREATE EXTERNAL TABLE test_tables.append_only (
    id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    value DOUBLE,
    dt DATE
)
STORED AS LAKESOUL
LOCATION '$LOC/append_only';
INSERT INTO test_tables.append_only
SELECT g.value AS id, CAST(g.value AS VARCHAR) AS name, g.value * 1.0 AS value, CAST('2024-01-01' AS DATE) AS dt
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.append_only
SELECT g.value + $((ROWS / 2)) AS id, CAST(g.value AS VARCHAR) AS name, g.value * 2.0 AS value, CAST('2024-06-01' AS DATE) AS dt
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 2. Hash primary key, single column. The second insert upserts half the keys.
--
DROP TABLE IF EXISTS test_tables.pk_single;
CREATE EXTERNAL TABLE test_tables.pk_single (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    value DOUBLE
)
STORED AS LAKESOUL
OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/pk_single';
INSERT INTO test_tables.pk_single
SELECT g.value AS id, CAST(g.value AS VARCHAR) AS name, g.value * 1.0 AS value
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.pk_single
SELECT g.value AS id, 'updated' AS name, 999.0 AS value
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 3. Composite hash primary key. Composite PK columns are also the bucket key.
--
DROP TABLE IF EXISTS test_tables.pk_composite;
CREATE EXTERNAL TABLE test_tables.pk_composite (
    k1 INT NOT NULL,
    k2 BIGINT NOT NULL,
    v DOUBLE,
    PRIMARY KEY (k1, k2)
)
STORED AS LAKESOUL
OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/pk_composite';
INSERT INTO test_tables.pk_composite
SELECT CAST(g.value % 1000 AS INT) AS k1, g.value / 1000 AS k2, g.value * 1.0 AS v
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.pk_composite
SELECT CAST(g.value % 1000 AS INT) AS k1, g.value / 1000 AS k2, 999.0 AS v
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 4. Range partitioned, no primary key (append-only partitioned table).
--
DROP TABLE IF EXISTS test_tables.range_partitioned;
CREATE EXTERNAL TABLE test_tables.range_partitioned (
    id BIGINT NOT NULL,
    part INT NOT NULL,
    v DOUBLE
)
STORED AS LAKESOUL
PARTITIONED BY (part)
LOCATION '$LOC/range_partitioned';
INSERT INTO test_tables.range_partitioned
SELECT g.value AS id, CAST(g.value % $PARTITIONS AS INT) AS part, g.value * 1.5 AS v
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.range_partitioned
SELECT g.value + $((ROWS / 2)) AS id, CAST(g.value % $PARTITIONS AS INT) AS part, g.value * 2.5 AS v
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 5. Hash primary key + range partition (merge/bucket key = partition + pk).
--
DROP TABLE IF EXISTS test_tables.pk_partitioned;
CREATE EXTERNAL TABLE test_tables.pk_partitioned (
    id BIGINT NOT NULL,
    part INT NOT NULL,
    v DOUBLE,
    PRIMARY KEY (id)
)
STORED AS LAKESOUL
PARTITIONED BY (part)
OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/pk_partitioned';
INSERT INTO test_tables.pk_partitioned
SELECT g.value AS id, CAST(g.value % $PARTITIONS AS INT) AS part, g.value * 2.0 AS v
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.pk_partitioned
SELECT g.value AS id, CAST(g.value % $PARTITIONS AS INT) AS part, 999.0 AS v
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 6. CDC table: a 'delete' row vanishes on read, 'update' replaces the version.
--    Final visible row count is ROWS/2.
--
DROP TABLE IF EXISTS test_tables.cdc_table;
CREATE EXTERNAL TABLE test_tables.cdc_table (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    op VARCHAR
)
STORED AS LAKESOUL
OPTIONS (
    'format.use_cdc' 'true',
    'format.cdc_column' 'op',
    'hashBucketNum' '$BUCKETS'
)
LOCATION '$LOC/cdc_table';
INSERT INTO test_tables.cdc_table
SELECT g.value AS id, CAST(g.value AS VARCHAR) AS name, 'insert' AS op
FROM generate_series(0, $((ROWS - 1))) AS g(value);
INSERT INTO test_tables.cdc_table
SELECT g.value AS id, 'deleted' AS name, 'delete' AS op
FROM generate_series(0, $((ROWS / 2 - 1))) AS g(value);

--
-- 7. Vector index table (IVF+RaBitQ). BIGINT PK + FLOAT[] column.
--
DROP TABLE IF EXISTS test_tables.vector_table;
CREATE EXTERNAL TABLE test_tables.vector_table (
    id BIGINT NOT NULL PRIMARY KEY,
    vec FLOAT[] NOT NULL
)
STORED AS LAKESOUL
OPTIONS (
    'hashBucketNum' '$BUCKETS',
    'vector_index_columns' '[{"column":"vec","dim":8,"nlist":16,"total_bits":7,"metric":"L2"}]'
)
LOCATION '$LOC/vector_table';
INSERT INTO test_tables.vector_table
SELECT CAST(g.value AS BIGINT) AS id,
       ARRAY[sin(g.value), cos(g.value), g.value * 0.001, 0.5, -0.5, 1.0, -1.0, 0.0] AS vec
FROM generate_series(0, $((VEC_ROWS - 1))) AS g(value);

--
-- 8. Vortex file format instead of the default parquet.
--
DROP TABLE IF EXISTS test_tables.vortex_table;
CREATE EXTERNAL TABLE test_tables.vortex_table (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    v DOUBLE
)
STORED AS LAKESOUL
OPTIONS ('file_format' 'vortex', 'hashBucketNum' '$BUCKETS')
LOCATION '$LOC/vortex_table';
INSERT INTO test_tables.vortex_table
SELECT CAST(g.value AS BIGINT) AS id, CAST(g.value AS VARCHAR) AS name, g.value * 0.5 AS v
FROM generate_series(0, $((ROWS - 1))) AS g(value);

--
-- 9. All-column-types table (nullable, no primary key).
--
DROP TABLE IF EXISTS test_tables.all_types;
CREATE EXTERNAL TABLE test_tables.all_types (
    c_bool BOOLEAN,
    c_i8 TINYINT,
    c_i16 SMALLINT,
    c_i32 INT,
    c_i64 BIGINT,
    c_f32 FLOAT,
    c_f64 DOUBLE,
    c_dec DECIMAL(18, 4),
    c_str VARCHAR,
    c_date DATE,
    c_ts TIMESTAMP,
    c_list INT[]
)
STORED AS LAKESOUL
LOCATION '$LOC/all_types';
INSERT INTO test_tables.all_types VALUES
    (true, 1, 2, 3, 4, 1.5, 2.5, 3.1415, 'hello',
     CAST('2024-01-01' AS DATE), CAST('2024-01-01 12:00:00' AS TIMESTAMP), ARRAY[1, 2, 3]),
    (false, -1, -2, -3, -4, -1.5, -2.5, -3.1415, 'world',
     CAST('2024-12-31' AS DATE), CAST('2024-12-31 23:59:59' AS TIMESTAMP), ARRAY[4, 5, 6]);
SQL

if [ "$WITH_TPCH" = "1" ]; then
cat >> "$SQL_FILE" <<SQL

--
-- 10. Full TPC-H set with primary keys (data volume controlled by SF).
--     Generated in ${TPCH_PARTS} partitions.
--
DROP TABLE IF EXISTS test_tables.tpch_nation;
CREATE EXTERNAL TABLE test_tables.tpch_nation (
    n_nationkey BIGINT NOT NULL, n_name STRING NOT NULL,
    n_regionkey BIGINT NOT NULL, n_comment STRING NOT NULL,
    PRIMARY KEY (n_nationkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_nation';
INSERT INTO test_tables.tpch_nation SELECT * FROM tpch_nation($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_region;
CREATE EXTERNAL TABLE test_tables.tpch_region (
    r_regionkey BIGINT NOT NULL, r_name STRING NOT NULL, r_comment STRING NOT NULL,
    PRIMARY KEY (r_regionkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_region';
INSERT INTO test_tables.tpch_region SELECT * FROM tpch_region($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_customer;
CREATE EXTERNAL TABLE test_tables.tpch_customer (
    c_custkey BIGINT NOT NULL, c_name STRING NOT NULL, c_address STRING NOT NULL,
    c_nationkey BIGINT NOT NULL, c_phone STRING NOT NULL, c_acctbal DECIMAL(15,2) NOT NULL,
    c_mktsegment STRING NOT NULL, c_comment STRING NOT NULL,
    PRIMARY KEY (c_custkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_customer';
INSERT INTO test_tables.tpch_customer SELECT * FROM tpch_customer($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_supplier;
CREATE EXTERNAL TABLE test_tables.tpch_supplier (
    s_suppkey BIGINT NOT NULL, s_name STRING NOT NULL, s_address STRING NOT NULL,
    s_nationkey BIGINT NOT NULL, s_phone STRING NOT NULL, s_acctbal DECIMAL(15,2) NOT NULL,
    s_comment STRING NOT NULL,
    PRIMARY KEY (s_suppkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_supplier';
INSERT INTO test_tables.tpch_supplier SELECT * FROM tpch_supplier($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_part;
CREATE EXTERNAL TABLE test_tables.tpch_part (
    p_partkey BIGINT NOT NULL, p_name STRING NOT NULL, p_mfgr STRING NOT NULL,
    p_brand STRING NOT NULL, p_type STRING NOT NULL, p_size INT NOT NULL,
    p_container STRING NOT NULL, p_retailprice DECIMAL(15,2) NOT NULL, p_comment STRING NOT NULL,
    PRIMARY KEY (p_partkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_part';
INSERT INTO test_tables.tpch_part SELECT * FROM tpch_part($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_partsupp;
CREATE EXTERNAL TABLE test_tables.tpch_partsupp (
    ps_partkey BIGINT NOT NULL, ps_suppkey BIGINT NOT NULL, ps_availqty INT NOT NULL,
    ps_supplycost DECIMAL(15,2) NOT NULL, ps_comment STRING NOT NULL,
    PRIMARY KEY (ps_partkey, ps_suppkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_partsupp';
INSERT INTO test_tables.tpch_partsupp SELECT * FROM tpch_partsupp($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_orders;
CREATE EXTERNAL TABLE test_tables.tpch_orders (
    o_orderkey BIGINT NOT NULL, o_custkey BIGINT NOT NULL, o_orderstatus STRING NOT NULL,
    o_totalprice DECIMAL(15,2) NOT NULL, o_orderdate DATE NOT NULL, o_orderpriority STRING NOT NULL,
    o_clerk STRING NOT NULL, o_shippriority INT NOT NULL, o_comment STRING NOT NULL,
    PRIMARY KEY (o_orderkey)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_orders';
INSERT INTO test_tables.tpch_orders SELECT * FROM tpch_orders($SF_FMT, $TPCH_PARTS);

DROP TABLE IF EXISTS test_tables.tpch_lineitem;
CREATE EXTERNAL TABLE test_tables.tpch_lineitem (
    l_orderkey BIGINT NOT NULL, l_partkey BIGINT NOT NULL, l_suppkey BIGINT NOT NULL,
    l_linenumber INT NOT NULL, l_quantity DECIMAL(15,2) NOT NULL, l_extendedprice DECIMAL(15,2) NOT NULL,
    l_discount DECIMAL(15,2) NOT NULL, l_tax DECIMAL(15,2) NOT NULL, l_returnflag STRING NOT NULL,
    l_linestatus STRING NOT NULL, l_shipdate DATE NOT NULL, l_commitdate DATE NOT NULL,
    l_receiptdate DATE NOT NULL, l_shipinstruct STRING NOT NULL, l_shipmode STRING NOT NULL,
    l_comment STRING NOT NULL,
    PRIMARY KEY (l_orderkey, l_linenumber)
) STORED AS LAKESOUL OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_lineitem';
INSERT INTO test_tables.tpch_lineitem SELECT * FROM tpch_lineitem($SF_FMT, $TPCH_PARTS);

--
-- TPC-H with an extra range partition (3 distinct return flags).
--
DROP TABLE IF EXISTS test_tables.tpch_lineitem_part;
CREATE EXTERNAL TABLE test_tables.tpch_lineitem_part (
    l_orderkey BIGINT NOT NULL, l_partkey BIGINT NOT NULL, l_suppkey BIGINT NOT NULL,
    l_linenumber INT NOT NULL, l_quantity DECIMAL(15,2) NOT NULL, l_extendedprice DECIMAL(15,2) NOT NULL,
    l_discount DECIMAL(15,2) NOT NULL, l_tax DECIMAL(15,2) NOT NULL, l_returnflag STRING NOT NULL,
    l_linestatus STRING NOT NULL, l_shipdate DATE NOT NULL, l_commitdate DATE NOT NULL,
    l_receiptdate DATE NOT NULL, l_shipinstruct STRING NOT NULL, l_shipmode STRING NOT NULL,
    l_comment STRING NOT NULL,
    PRIMARY KEY (l_orderkey, l_linenumber)
) STORED AS LAKESOUL PARTITIONED BY (l_returnflag)
OPTIONS ('hashBucketNum' '$BUCKETS')
LOCATION '$LOC/tpch_lineitem_part';
INSERT INTO test_tables.tpch_lineitem_part SELECT * FROM tpch_lineitem($SF_FMT, $TPCH_PARTS);
SQL
fi

cat >> "$SQL_FILE" <<'SQL'

--
-- Smoke checks (row counts printed by the console).
--
SELECT COUNT(*) AS append_only FROM test_tables.append_only;
SELECT COUNT(*) AS pk_single FROM test_tables.pk_single;
SELECT COUNT(*) AS pk_composite FROM test_tables.pk_composite;
SELECT COUNT(*) AS range_partitioned FROM test_tables.range_partitioned;
SELECT COUNT(*) AS pk_partitioned FROM test_tables.pk_partitioned;
SELECT COUNT(*) AS cdc_visible FROM test_tables.cdc_table;
SELECT COUNT(*) AS vector_rows FROM test_tables.vector_table;
SELECT COUNT(*) AS vortex_rows FROM test_tables.vortex_table;
SELECT * FROM test_tables.range_partitioned WHERE part = 0 ORDER BY id LIMIT 3;
SELECT id FROM test_tables.vector_table ORDER BY array_distance(vec, ARRAY[0.0, 1.0, 0.0, 0.5, -0.5, 1.0, -1.0, 0.0]) LIMIT 5;
SQL

if [ "$WITH_TPCH" = "1" ]; then
cat >> "$SQL_FILE" <<'SQL'
SELECT COUNT(*) AS tpch_lineitem FROM test_tables.tpch_lineitem;
SELECT COUNT(*) AS tpch_orders FROM test_tables.tpch_orders;
SELECT COUNT(*) AS tpch_customer FROM test_tables.tpch_customer;
SELECT COUNT(*) AS tpch_part FROM test_tables.tpch_part;
SELECT COUNT(*) AS tpch_partsupp FROM test_tables.tpch_partsupp;
SELECT COUNT(*) AS tpch_supplier FROM test_tables.tpch_supplier;
SELECT COUNT(*) AS tpch_nation FROM test_tables.tpch_nation;
SELECT COUNT(*) AS tpch_region FROM test_tables.tpch_region;
SELECT COUNT(*) AS tpch_lineitem_part FROM test_tables.tpch_lineitem_part;
SQL
fi

echo "==> generated SQL: $SQL_FILE"
echo "==> rows=$ROWS vec_rows=$VEC_ROWS partitions=$PARTITIONS sf=$SF with_tpch=$WITH_TPCH loc=$LOC"

if [ -n "${CONSOLE_BIN:-}" ]; then
    exec "$CONSOLE_BIN" --worker-threads "$WORKER_THREADS" "$@" --file "$SQL_FILE"
else
    exec cargo run --quiet --bin lakesoul-console -- \
        --worker-threads "$WORKER_THREADS" "$@" --file "$SQL_FILE"
fi
