# SPDX-FileCopyrightText: 2026 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Core Release

on:
  pull_request:
    branches:
      - "release/**"
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  actions: read
  attestations: write
  contents: write
  id-token: write
jobs:
  release:
    uses: ./.github/workflows/release-build.yml
    with:
      publish: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      tag: ${{ github.event_name == 'push' && github.ref_name || '' }}
    secrets: inherit
