name: Cross build

on:
  push:
    paths-ignore:
      - "javadoc/**"
      - "website/**"
      - "**.md"
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - "javadoc/**"
      - "website/**"
      - "**.md"
    branches:
      - 'main'
      - 'release/**'
  workflow_dispatch:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: '--manifest-path native-io/Cargo.toml --target x86_64-unknown-linux-gnu --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-unknown-linux-gnu
          path: ./native-io/target/x86_64-unknown-linux-gnu/release/liblakesoul_io_c.so

  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--manifest-path native-io/Cargo.toml --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-pc-windows-msvc
          path: ./native-io/target/release/lakesoul_io_c.dll

  build-macos-x86_64:
    runs-on: macos-latest
    steps:
      - name: Install automake
        run: brew install automake
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--manifest-path native-io/Cargo.toml --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-apple-darwin
          path: ./native-io/target/release/liblakesoul_io_c.dylib

  build-maven-package:
    runs-on: ubuntu-latest
    needs: [ build-linux-x86_64, build-windows-x86_64, build-macos-x86_64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-unknown-linux-gnu
          path: ./native-io/target/release/
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-apple-darwin
          path: ./native-io/target/release/
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-pc-windows-msvc
          path: ./native-io/target/release/
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.x"
      - name: Build with Maven
        run: |
          MAVEN_OPTS="-Xmx4000m" mvn -q -B package --file pom.xml -Pcross-build -DskipTests -Dmaven.test.skip=true
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: maven-package-upload
          path: |
            lakesoul-spark/target/lakesoul-spark-*.jar
            lakesoul-flink/target/lakesoul-flink-*.jar
          retention-days: 3
          if-no-files-found: error
